### ISSUE TITLE
more fotorama modifications

### ISSUE THREAD

**Issue by jobe451** [jobe451/PencilBlue-Picture-Service#6]
Check and aply these pull requests
https://github.com/artpolikarpov/fotorama/pull/337
https://github.com/artpolikarpov/fotorama/pull/393

**Comment by tyssen** [comment]
+1 for #337: I'd like access to srcset support.

**Comment by jobe451** [comment]
temlate modified with working srcset

**Comment by jobe451** [comment]
#393 not added, console.log seem to get removed by grunt build process.

**Comment by jobe451** [comment]
For #337 to work, the various srcset widht variations must be configured in settings "Valid_Width_List"
